services:
  wipi.registration.form.type:
    class: Site\UserBundle\Form\RegistrationFormType
    arguments: [%fos_user.model.user.class%]
    tags:
        - { name: form.type, alias: wipi_user_registration_form }

  wipi.twig.images_extension:
    class: Site\BaseBundle\Twig\ImageExtension
    tags: [ { name: twig.extension } ]
    arguments: [@service_container]

  wipi.translator:
    class: Site\BaseBundle\Helper\TranslationHelper
    arguments: [@service_container]


  wipi.word.steps_handler:
    class: Site\BaseBundle\Form\Handler\WordStepsHandler
    calls:
      - [setContainer, [@service_container]]